name = "martial-arts-manager"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# JWT_SECRET is now securely stored as an encrypted secret via:
# wrangler pages secret put JWT_SECRET
# This is available in both production and preview environments

[env.production]
d1_databases = [
  { binding = "DB", database_name = "martial-arts-db", database_id = "4ad2408a-54e1-45e3-a352-42be3e284299" }
]
r2_buckets = [
  { binding = "AVATARS", bucket_name = "martial-arts-manager-bucket" }
]

[[d1_databases]]
binding = "DB"
database_name = "martial-arts-db"
database_id = "4ad2408a-54e1-45e3-a352-42be3e284299"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "martial-arts-manager-bucket"