name = "martial-arts-manager"
compatibility_date = "2023-12-01"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "martial-arts-db", database_id = "4ad2408a-54e1-45e3-a352-42be3e284299" }
]

[[d1_databases]]
binding = "DB"
database_name = "martial-arts-db"
database_id = "4ad2408a-54e1-45e3-a352-42be3e284299"