export { default as ProfileSettings } from './ProfileSettings';
export { default as AccountPreferencesSettings } from './AccountPreferencesSettings';
export { default as DojoSettings } from './DojoSettings';
export { default as NotificationSettings } from './NotificationSettings';
export { default as AppearanceSettings } from './AppearanceSettings';
export { default as MobileSettings } from './MobileSettings';
export { default as PaymentSettings } from './PaymentSettings';
export { default as DataBackupSettings } from './DataBackupSettings';
export { default as MercadoPagoSettings } from './MercadoPagoSettings';